### ISSUE TITLE
Can't find extension to start using

### ISSUE THREAD

**Issue by awakekat** [swmitra/html-designer#2]
I have installed your awesome extension, restarted Brackets, been through the entire menu and don't see an icon on the left. Can you explain how to find it to use it?

{{!!!PLEASE!!!}} put in the documentation that the word "CodeView" at the bottom of the UI has a dropdown that allows the user to switch to "DesignView" to use it.

**Comment by swmitra** [comment]
I have updated the documentation and created a new section "How to enable Design Mode?" before going into features. I hope it's likely to be noticed now in order to make this feature likable :-) 
![viewoptionmenu](https://cloud.githubusercontent.com/assets/12087205/8795638/2a17ec82-2fac-11e5-8bde-d989286c23ad.png)

**Comment by awakekat** [comment]
Thanks so much - it will definitely help others. I have used computers for a long time and that important step in your documentation will cure a lot of confusion and keep the plugin installed.

Happy coding!
